name: Test Fractional and Expression
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - name: Checkout submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check for bad words
        run: "! grep -R -n -w -f .bad_words src libraries"
      - name: Run clang format
        run: "find . -iname *.h -o -iname *.hpp -o -iname *.cpp -exec clang-format --dry-run --Werror -style=file {} +"
      - name: Getting catch2
        run: |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install
          sudo apt-get install -y clang-tidy catch2

      - name: Build default
        run: mkdir build && cmake -S. -Bbuild -DUSE_CLANG_TIDY=TRUE -DTESTS_BUILD_TYPE=NONE -DCMAKE_BUILD_TYPE=Release && cmake --build build
      - name: Run Tests
        timeout-minutes: 3
        run: ./build/test

      - name: Build ASAN
        run: mkdir build_ASAN && cmake -S. -Bbuild_ASAN -DTESTS_BUILD_TYPE=ASAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_ASAN
      - name: Run ASAN Tests
        timeout-minutes: 3
        run: ./build_ASAN/test

      - name: Build USAN
        run: mkdir build_USAN && cmake -S. -Bbuild_USAN -DTESTS_BUILD_TYPE=USAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_USAN
      - name: Run USAN Tests
        timeout-minutes: 3
        run: ./build_USAN/test

      - name: Build MSAN
        run: mkdir build_MSAN && cmake -S. -Bbuild_MSAN -DTESTS_BUILD_TYPE=MSAN -DCMAKE_BUILD_TYPE=Debug && cmake --build build_MSAN
      - name: Run MSAN Tests
        timeout-minutes: 3
        run: ./build_MSAN/test
